name: "Get the number of this PR"
description: "Get the number of this PR"
author: Štefan Ľupták
branding:
  icon: monitor
  color: green
outputs:
  pr_number:
    description: Number of the PR
    value: ${{ steps.get_pr_number.outputs.pr_number }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: get_pr_number
      run: |
        echo "Retrieving PR number"
        pr_number=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "PR number is $pr_number"
        echo ::set-output name=pr_number::"$pr_number"
